version: '3.3'

services:
  employeeInfodb:
    image: mysql
    volumes:
      - employeeInfodb_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users
      MYSQL_USER: eric
      MYSQL_PASSWORD: admin
    networks:
      - persist
volumes:
  employeeInfodb_data: {}
networks:
  persist: {}